// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bboljxxbauwseqthpouv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJib2xqeHhiYXV3c2VxdGhwb3V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5Mzk0MTMsImV4cCI6MjA2MzUxNTQxM30.vGbpnQmwD5v16Oon2YBveAKkcePd4psjaSoR7hKxfVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);